### ISSUE TITLE
使用Sqlite 账号密码是什么

### ISSUE THREAD

**Issue by icocoding** [dromara/mayfly-go#100]
使用Sqlite 账号密码是什么

**Comment by may-fly** [comment]
跟mysql一样  admin  admin123.

**Comment by icocoding** [comment]
有个.真是…



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: may-fly ***@***.***&gt;
发送时间: 2024年11月1日 16:05
收件人: dromara/mayfly-go ***@***.***&gt;
抄送: CoCoding ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dromara/mayfly-go] 使用Sqlite 账号密码是什么 (Issue #100)





 
跟mysql一样  admin  admin123.
