### ISSUE TITLE
标签树右侧空白

### ISSUE THREAD

**Issue by gcdd1993** [dromara/mayfly-go#103]
版本是1.9.2，点击标签，右侧没有信息
![image](https://github.com/user-attachments/assets/3329b490-7351-4a26-a400-6b62c02d00e6)

版本1.9.1，点击标签，右侧出现标签信息
![image](https://github.com/user-attachments/assets/c34024ad-971a-488e-a8c0-709207adce71)

**Comment by may-fly** [comment]
重新拉包已修复
