### ISSUE TITLE
PostgreSQL 连接后无法显示表数据

### ISSUE THREAD

**Issue by wdd817** [dromara/mayfly-go#39]
有表 UserMail , 执行以下 SQL 可以查询数据条数
SELECT COUNT(*) count FROM "UserMail" LIMIT 1;
但是在数据管理中点开表会提示报错
![image](https://github.com/may-fly/mayfly-go/assets/4275164/95c2a973-33c6-496a-8594-d3fc1a2f7b1a)

系统数据库的字符排序为 utf8mb4-bin

**Comment by may-fly** [comment]
可能是表名大小写问题
