### ISSUE TITLE
在SQL 脚本查询中创建表时不支持 current_timestamp()

### ISSUE THREAD

**Issue by kanzihuang** [dromara/mayfly-go#64]
解析以下 SQL 脚本生成的 SQL 语句为 "create table tbl", 缺少字段信息。
create table tbl (
	id bigint(20),
	create_at datetime DEFAULT current_timestamp()
);

**Comment by liuzongyang255** [comment]
DEFAULT CURRENT_TIMESTAMP   不要后面的括号()

**Comment by kanzihuang** [comment]
V1.5.3  问题已解决
