### ISSUE TITLE
Redis 数据操作时，scan 命令的风险

### ISSUE THREAD

**Issue by lntusl** [dromara/mayfly-go#97]
当在输入框输入字符长度超过 10 个且带了*的通配符时，count 会自动改为当前dbSize的 1/10，而且就算是手动把 count 改为一个比较小的值后 count 依旧会被自动计算为dbSize的 1/10。

这个future 在生产中会带来很大的性能隐患。

![image](https://github.com/dromara/mayfly-go/assets/10673512/3d0d5d69-6a2e-4885-93c0-8425b15bdcd5)

**Comment by lntusl** [comment]
修改标题

**Comment by may-fly** [comment]
获取方式已调整
