### ISSUE TITLE
{{.ID}} 脚本不支持双括号格式

### ISSUE THREAD

**Issue by wws-test** [dromara/mayfly-go#98]
![image](https://github.com/dromara/mayfly-go/assets/39082410/9f99c2da-c9eb-4fb9-99c2-522b81f0634d)
实际脚本写法
![image](https://github.com/dromara/mayfly-go/assets/39082410/b1f5b1a1-045d-4cc8-aaee-b473eb6623b1)
在liunx上运行正常

**Comment by may-fly** [comment]
{{}}是golang中模板字符串占位符的引用

**Comment by wws-test** [comment]
ok  你的邮件我已经收到。

**Comment by wws-test** [comment]
ok  你的邮件我已经收到。
